### ISSUE TITLE
New code for the same project 

### ISSUE THREAD

**Issue by payallenka** [ashwin3005/Password#5]
I have been through your code and I believe I can write a better code rather shorter that would perform the same work, i.e., to generate passwords that are easy to remember. That code would demand one input from the user to help the program create the same. 
I wish to participate in hacktoberfest. If you like my proposal then it will be great if you'll add the hactoberfest tag and assign me the issue.

**Comment by ashwin3005** [comment]
okay go ahead,
but create a separate python file.

**Comment by ashwin3005** [comment]
This is just a fun project.

**Comment by payallenka** [comment]
Got it, thank you
